### ISSUE TITLE
Cannot archive project in Xcode 13 - input file 'R.generated.swift' was modified during the build

### ISSUE THREAD

**Issue by kaiengelhardt** [mac-cain13/R.swift#719]
Greetings!
A project that worked perfectly fine in Xcode 12.5.1 and earlier doesn't archive anymore in Xcode 13 Beta 5. It fails with this error.

```
CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'Vectornator' from project 'Vectornator')
<Build command>
error: input file '/PrivatePath/Other Sources/R.generated.swift' was modified during the build
error: input file '/PrivatePath/Other Sources/R.generated.swift' was modified during the build
Command CompileSwiftSources failed with a nonzero exit code
```

The project is an iOS app with a Catalyst version. iOS builds, runs and archives fine. Catalyst builds and runs fine, but fails to archive. Here's the build phase setup.
<img width="863" alt="Bildschirmfoto 2021-09-13 um 18 18 31" src="https://user-images.githubusercontent.com/966076/133120355-e224ec24-f04f-41bf-8585-5db09ed0a1ea.png">

Does anyone have any idea what's going wrong?
<img width="1061" alt="Bildschirmfoto 2021-09-13 um 18 15 40" src="https://user-images.githubusercontent.com/966076/133120117-28e951a7-3f93-4898-9cc7-62fa37c95816.png">

I will retest with Xcode 13 RC tomorrow and update the issue.

**Comment by kaiengelhardt** [comment]
Okay, I tested this with Xcode 13RC and the same issue occurs. When I surround the R.swift build with `sleep 10` commands,  the situation somewhat improves – the build only fails sometimes then.

**Comment by amvfortuna** [comment]
I think it's worth noting that this happens when you update the command line tools to Xcode 13. Changing it back to Xcode 12.5 does not generate the error.

I think it's somewhat similar to issue #480 when the new build system was introduced.

**Comment by amvfortuna** [comment]
> I think it's worth noting that this happens when you update the command line tools to Xcode 13. Changing it back to Xcode 12.5 does not generate the error.

Never mind, it's still happening even when the command line tool is pointing to Xcode 12.5, though less frequent compared to Xcode 13.

**Comment by alessiolapenna** [comment]
This is not only in Archive. I'm having this problem with an iOS app even running in simulator. If the file R.generated is already there the build fails. So only the first build after a clean succeed.
The only way I found to avoid cleaning every time is to move the R.swift build phase in the build phases queue. If i move it one step up or down it compiles just fine for one time. I think it would be solve by just deleting the R.generated file at the beginning of every build.

**Comment by raxityo** [comment]
For me, it happens arbitrarily (although, there could be some pattern in the way I change or do not change code) regardless of running in a simulator or physical device.

Other than cleaning and rebuilding, the workaround I have found is to check/uncheck one of these check boxes and trying the build again:
<img width="977" alt="Screen Shot 2021-09-16 at 11 30 08 AM" src="https://user-images.githubusercontent.com/767683/133641150-79e27407-8382-49ec-8bd5-3cd785046949.png">

**Comment by alessiolapenna** [comment]
Another workaround I found was moving the R.swift script phase up or down one step in the buildphases queue, before building.

**Comment by alessiolapenna** [comment]
For me this is solved with the official XCode13 release.

**Comment by VanjaPopovic** [comment]
I have the same issue archiving iOS using XCode 13 release.

**Comment by hanshantao** [comment]
> I have the same issue archiving iOS using XCode 13 release.
me too

**Comment by hujunfeng** [comment]
I'm also experiencing the same issue with the official release of Xcode 13.

**Comment by alessiolapenna** [comment]
Hi,

I solved this by adding a new build phase that always deletes the R.generated file of the previous build. 
I added it as the first step after the Dependencies.
Pay attention to uncheck the "Based on dependencies analysis" flag, as we want this script to run every time we build.
Hope this helps everybody.
Cheers.

[](url
![Schermata 2021-09-23 alle 10 00 35](https://user-images.githubusercontent.com/3438105/134440965-72280d7f-5f38-4272-b771-bb59c8b254e2.png)
)

**Comment by iAmrSalman** [comment]
+1

**Comment by Parithi** [comment]
+1

**Comment by OliviaHourcade-o** [comment]
+1

**Comment by haduyenhoa** [comment]
It seems the issue come from the value of **buildActionMask** is wrongly set after opening project with Xcode 13. 
Try this work around. it's working for me: unselect the option "Based on dependency analysis" for the script to generate **R.generated.swift** file (screen-shot)
This will reset the buildActionMask to the right value.

![Screenshot 2021-09-28 at 09 59 17](https://user-images.githubusercontent.com/5282047/135047849-554c7e9f-9735-424a-8120-c3cbe9edb740.png)
![Screenshot 2021-09-28 at 09 59 26](https://user-images.githubusercontent.com/5282047/135047857-351dde46-7121-4334-9c38-094bdfca4ac4.png)

**Comment by pnzr00t** [comment]
> is wrongly set after opening project with Xcode 13.
> Try this work around. it's working for me: unselect the optio

This solution is working on few severals build, after that this error appears again. And you must again turn on/off this options.

**Comment by tomlokhorst** [comment]
I've been looking into this issue, unfortunately this appears to be a bug in Xcode 13.

I've tried the workarounds mentioned in this thread as well what was mentioned in [this stackoverflow question](https://stackoverflow.com/questions/69256241/xcode-13-error-input-file-was-modified-during-the-build) and [this WooCommerce PR](https://github.com/woocommerce/woocommerce-ios/pull/5049). None of them work reliably.

What does _not_ fix the issue on Xcode 13:

- Toggling "For install builds", and "Based on dependency analysis" in the build phase
- Using Output File Lists (.xcfilelist) instead of Output Files directly
- Not specifying the Output File

The issue appears to be that Xcode 13 executes "Run Script" build phase way to often, occasionally in parallel with "Compile Sources" build phase. See this example project: [XcodeScriptBuildPhaseIssue](https://github.com/tomlokhorst/XcodeScriptBuildPhaseIssue).

I will file a TSI with Apple, asking for a workaround, but this appears to be a bug in Xcode 13.

**Comment by vfn** [comment]
I found a similar issue with one of my build script phases and the workaround in my case was to generate the "new" file to a temporary location, and then check the "new" file against the existing one using a command like [cmp](https://ss64.com/bash/cmp.html)

```
if ! cmp EXISTING_FILE NEW_FILE >/dev/null 2>&1; then
  # Move new file to replace old one
fi
```
Or with [diff](https://ss64.com/bash/diff.html)
```
if diff -q EXISTING_FILE NEW_FILE; then
  # Move new file to replace old one
fi
```

This should prevent the build phase from "touching" the existing file, unless there was a change.

**Comment by tylerjames** [comment]
Yet more evidence that Xcode 13 is hot garbage and should never have been released in this state.

**Comment by RockinGarg** [comment]
Does this means no workaround yet and should downgrade Xcode to make the project run?

**Comment by pnzr00t** [comment]
> Does this means no workaround yet and should downgrade Xcode to make the project run?

Yes, but how i may downgrade IOS version in iphone?

**Comment by zigdanis** [comment]
My workaround:
* Uncheck "Based on dependency analysis" option for the R.swift Run Script
* Change target's build number on every new Build.

Right now I do it manually, but I guess there is a way to automate those build number changes

**Comment by raxityo** [comment]
My workaround for now is to not run R.swift generation step in local environment and only running it in the CI. The CI builds won't have the build cache that creates this problem.

Locally, we only have to run R.swift generator when any resources change. I automated that by detecting changes to the resources using file watcher and running R.swift generator.

It does the job for now without requiring any manual intervention.

**Comment by tomlokhorst** [comment]
I've found what appears to be a stable workaround:

Create a separate target of type "External Build System" that does the call to R.swift, and configure that target as a dependency of the regular target.
I'll investigate a bit further to see if this works in multiple situations. If it works in all cases, I'll update the documentation with detailed steps.

Note: This requires 5.5.0-alpha.8, because it needs to pass in some extra arguments (infoPlistFile and target) via commandline arguments.

**Comment by kiritokatklian** [comment]
@tomlokhorst could you please share the steps you took to get it to work using the External Build System target?

**Comment by tomlokhorst** [comment]
**Update:**

I filed a TSI with Apple Developer Technical Support and got a reply from the same engineer who helped [three years ago](https://github.com/mac-cain13/R.swift/issues/456) with the update to Xcode 10. They reiterated that a Run Script build phase is not intended to be used for code generation, it is not a supported scenario.

Apple DTS made two suggestions:

1. Place a script in a Build pre-action in the schema
2. Consider using a custom build rule, as presented in this years WWDC: https://developer.apple.com/videos/play/wwdc2021/10210/?time=379

I'm not a fan of the pre-action in the schema, because I maintain multiple schemas (but you can use it if you like). And the build rule is not re-run on incremental builds, if none of the inputs change.

---

### R.swift 6.0.0

I'm working on R.swift version 6.0.0 with two usage scenarios: Either run R.swift manually (without Xcode), or use a separate External Build System target.

These are the two new features of version 6:

1. All environment variables from Xcode build phase can now be passed in via command line arguments, so you can run `rswift` outside of Xcode
2. A new `print-command` command has been added, as an alternative to the exising `generate` command. This is to help with the migration, because now `rswift` requires a lot more arguments.


#### Run R.swift manually outside of Xcode:

To run R.swift by hand, without integrating with Xcode:

1. Change your existing Run Script, change `rswift generate` to `rswift print-command --arguments portable`
   <img width="1226" alt="Screenshot 2021-10-06 at 13 20 25" src="https://user-images.githubusercontent.com/75655/136193718-9c1cfdca-38ac-4bc6-b02a-fbf4d072afbc.png">

2. When building, this will generate this output:
   <img width="929" alt="Screenshot 2021-10-06 at 13 21 41" src="https://user-images.githubusercontent.com/75655/136193781-e1cfd1a4-7c48-4abb-bfd3-8931aa606a03.png">

3. Copy that command and use that from now on, whenever you want to update the R.generated.swift file
4. Delete the existing Run script build phase


#### Run R.swift from a separate target

To get `rswift` to run only once, before every new build:

1. Change your existing Run Script, change `rswift generate` to `rswift print-command --arguments xcode`
   <img width="1212" alt="Screenshot 2021-10-06 at 13 31 10" src="https://user-images.githubusercontent.com/75655/136194732-70808381-8c04-44c8-9d74-1a052bd8f8b9.png">

2. When building, this will generate this output:
   <img width="1234" alt="Screenshot 2021-10-06 at 13 32 01" src="https://user-images.githubusercontent.com/75655/136194765-e5562133-c829-48ac-ac64-db9f1d27319b.png">

3. Copy that command for later use
4. Delete the existing Run script build phase
5. Add a new target called "MyApp-Rswift", using the "Other > External Build System" Template
   <img width="737" alt="Screenshot 2021-10-06 at 13 34 42" src="https://user-images.githubusercontent.com/75655/136194964-c03bdc0c-8203-4a83-b434-d0c626e88718.png">
6. Configure the External Build Tool Configuration using the arguments you've copied in step 3
   <img width="960" alt="Screenshot 2021-10-06 at 13 36 06" src="https://user-images.githubusercontent.com/75655/136195172-af1500b1-e691-4fe7-8831-760f90f94f81.png">
7. In the Dependencies list of your original MyApp target, add the new MyApp-Rswift target as a dependency
   <img width="829" alt="Screenshot 2021-10-06 at 13 37 49" src="https://user-images.githubusercontent.com/75655/136195419-4c6f9c3f-1310-41b3-a432-eb6923144e2f.png">

Now, whenever you build MyApp target, Xcode will first run the External Build Tool configured in that new target, before starting with the build of the app.

This was inspired my the WWDC 2018 session [Building Faster in Xcode](https://developer.apple.com/videos/play/wwdc2018/408)

---

I've created a [6.0.0 alpha release](https://github.com/mac-cain13/R.swift/releases) for testing, I'm still working on the documentation, before making the final 6.0.0 release.

**Comment by qubblr** [comment]
@tomlokhorst `indexbuild` check works consistently for local builds but breaks CI builds (AppCenter Xcode 13).

**Comment by tomlokhorst** [comment]
I've released R.swift 6.0.0. This has build-in support for checking against Index builds.

So updating the script is no longer necessary. Although some updates to the build phase are needed: https://github.com/mac-cain13/R.swift/blob/master/Documentation/Migration.md#upgrading-to-60

**Comment by EmDee** [comment]
@tomlokhorst Will the [R.swift.library](https://github.com/mac-cain13/R.swift.Library) also be updated to use the latest version `6.0.0`/`6.1.0` with the fix?

**Comment by tomlokhorst** [comment]
@EmDee This is purely a change in the `rswift` tool itself, no changes are needed in R.swift.Library

**Comment by nkavian** [comment]
I'm still encountering this with R 7.5.0 using SPM and Xcode 15.3.

**Comment by Booharin** [comment]
I'm encountering this with R 7.8.0 using SPM and Xcode 16.0. Builds work but Archives fail.
